version: '2'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: budgetme

  web:
    build: .
    command: ./bin/docker_server.sh
    environment:
      DB_PASSWORD: password
      DB_USER: budgetme
      DB_HOST: db
      RACK_ENV: development
      PORT: 3000
    volumes:
      - .:/myapp
      - bundle-volume:/bundles
    ports:
      - "3300:3000"
    depends_on:
      - db

volumes:
  bundle-volume:
