version: '2'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: budgetme

  redis:
    image: redis:3.2-alpine

  web:
    build: .
    command: ./bin/docker_server.sh
    environment:
      DB_PASSWORD: password
      DB_USER: budgetme
      DB_HOST: db
    volumes:
      - .:/myapp
      - bundle-volume:/bundles
    ports:
      - "3300:3000"
    depends_on:
      - db

volumes:
  bundle-volume:
