default: &default
  adapter: mysql2
  username: <%= ENV.fetch("BUDGET_ME_DB_USER") { 'root' } %>
  password: <%= ENV.fetch("BUDGET_ME_DB_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("BUDGET_ME_DB_HOST") { 'localhost' } %>
  reconnect: true

development:
  <<: *default
  database: budget_me_development

test:
  <<: *default
  database: budget_me_test

production:
  <<: *default
  database: budget_me
  # url: <%= ENV['DATABASE_URL'] %>
